<?php
/**
 * Lightweight two-language support (Indonesian / English).
 *
 * Usage in a page:
 *     require_once __DIR__ . '/_lang.php';
 *     <?= t('Daftar Supplier') ?>
 *
 * The Indonesian copy doubles as the translation key, so any string that has
 * not been translated yet still renders correctly instead of showing a raw
 * key. Switching is done with ?lang=en / ?lang=id and remembered in the
 * session plus a cookie, so the choice survives a new browser session.
 */

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if (!defined('TV_LANGS')) {
    define('TV_LANGS', ['id' => 'Indonesia', 'en' => 'English']);
}

// ---------------------------------------------------------------------------
// Resolve the active language
// ---------------------------------------------------------------------------
if (isset($_GET['lang']) && array_key_exists($_GET['lang'], TV_LANGS)) {
    $_SESSION['tv_lang'] = $_GET['lang'];
    setcookie('tv_lang', $_GET['lang'], time() + 60 * 60 * 24 * 365, '/');
} elseif (!isset($_SESSION['tv_lang'])) {
    $_SESSION['tv_lang'] = (isset($_COOKIE['tv_lang']) && array_key_exists($_COOKIE['tv_lang'], TV_LANGS))
        ? $_COOKIE['tv_lang']
        : 'id';
}

if (!function_exists('tv_lang')) {
    function tv_lang()
    {
        return $_SESSION['tv_lang'] ?? 'id';
    }
}

// ---------------------------------------------------------------------------
// Dictionary: Indonesian source string => English translation
// ---------------------------------------------------------------------------
$GLOBALS['TV_DICT'] = [

    /* ---- navigation & shared chrome ---- */
    'Beranda'                => 'Home',
    'Tentang Kami'           => 'About Us',
    'Hotel'                  => 'Hotels',
    'Pesawat'                => 'Flights',
    'Fitur'                  => 'Features',
    'Tim Kami'               => 'Our Team',
    'Kontak'                 => 'Contact',
    'Riwayat'                => 'History',
    'Logout'                 => 'Log Out',
    'Profil Saya'            => 'My Profile',
    'Pesanan Saya'           => 'My Orders',
    'Daftar Pembelian'       => 'Purchase List',
    'Keamanan'               => 'Security',
    'Pengaturan'             => 'Settings',
    'Menu akun'              => 'Account menu',
    'Bahasa'                 => 'Language',

    /* ---- supplier registration ---- */
    'Daftar Supplier'        => 'Supplier Registration',
    'Bergabunglah dengan jaringan supplier profesional kami'
                             => 'Join our network of professional suppliers',
    'Nama Depan'             => 'First Name',
    'Nama Belakang'          => 'Last Name',
    'Username'               => 'Username',
    'Email'                  => 'Email',
    'Nomor Telepon'          => 'Phone Number',
    'Nama Perusahaan'        => 'Company Name',
    'Alamat Perusahaan'      => 'Company Address',
    'NPWP / Tax ID'          => 'Tax ID',
    'Password'               => 'Password',
    'Konfirmasi Password'    => 'Confirm Password',
    'Sudah punya akun?'      => 'Already have an account?',
    'Masuk di sini'          => 'Sign in here',
    'Kembali ke Beranda'     => 'Back to Home',
    'Nama depan Anda'        => 'Your first name',
    'Nama belakang Anda'     => 'Your last name',
    'Username unik untuk login' => 'A unique username for signing in',
    'Email bisnis Anda'      => 'Your business email',
    'Nomor telepon bisnis'   => 'Business phone number',
    'Nama perusahaan atau bisnis' => 'Company or business name',
    'Alamat lengkap perusahaan'   => 'Full company address',
    'Nomor NPWP atau Tax ID' => 'Tax identification number',
    'Buat password yang kuat' => 'Create a strong password',
    'Ulangi password Anda'   => 'Repeat your password',
    'Informasi Pribadi'      => 'Personal Information',
    'Informasi Perusahaan'   => 'Company Information',
    'NPWP / Tax ID'          => 'Tax ID',
    'DAFTAR SEBAGAI SUPPLIER' => 'REGISTER AS SUPPLIER',
    'Daftar Sebagai Supplier' => 'Register as Supplier',

    /* ---- supplier registration: server messages ---- */
    'Mohon isi semua field yang wajib (ditandai *)!'
                             => 'Please fill in all required fields (marked *).',
    'Password dan Konfirmasi Password tidak cocok!'
                             => 'Password and confirmation do not match.',
    'Password harus minimal 6 karakter!'
                             => 'Password must be at least 6 characters.',
    'Email sudah terdaftar sebagai supplier!'
                             => 'That email is already registered as a supplier.',
    'Username sudah digunakan!'
                             => 'That username is already taken.',
    'Registrasi supplier berhasil! Silakan login.'
                             => 'Supplier registration successful. Please sign in.',
    'Error saat registrasi: ' => 'Registration error: ',

    /* ---- sign in / sign up ---- */
    'Masuk'                  => 'Sign In',
    'Daftar'                 => 'Sign Up',
    'Lupa Password?'         => 'Forgot Password?',
    'Belum punya akun?'      => "Don't have an account yet?",
    'Pilih Tipe Akun'        => 'Select Account Type',
    'Customer'               => 'Customer',
    'Supplier'               => 'Supplier',
    'Pesan perjalanan dan pengalaman' => 'Book trips and experiences',
    'Tawarkan layanan perjalanan'     => 'Offer travel services',

    /* ---- hotel search & booking ---- */
    'Kota dan tujuan'        => 'City or destination',
    'Kota dan tujuan hotel'  => 'City, hotel or landmark',
    'Check-In:'              => 'Check-in:',
    'Check-Out:'             => 'Check-out:',
    'Durasi:'                => 'Duration:',
    'Tamu dan Kamar:'        => 'Guests and Rooms:',
    'malam'                  => 'night(s)',
    'Dewasa'                 => 'Adults',
    'Anak'                   => 'Children',
    'Kamar'                  => 'Rooms',
    'Selesai'                => 'Done',
    'Cari Hotel'             => 'Search Hotels',
    'Lihat Detail'           => 'View Details',
    'Pesan Sekarang'         => 'Book Now',
    'Kembali'                => 'Back',
    'Lanjutkan'              => 'Continue',
    'Lewati Layanan'         => 'Skip Add-ons',
    'Lanjutkan ke Pembayaran' => 'Continue to Payment',
    'Batalkan Pemesanan'     => 'Cancel Booking',
    'Saya Sudah Bayar'       => "I've Paid",
    'Detail Pesanan'         => 'Order Details',
    'Penawaran Layanan'      => 'Add-on Services',
    'Pembayaran'             => 'Payment',
    'Konfirmasi'             => 'Confirmation',
    'Ringkasan Pesanan'      => 'Order Summary',
    'Total Pembayaran'       => 'Total Payment',
    'per malam'              => 'per night',
    'Tersedia'               => 'Available',
    'Habis'                  => 'Sold out',

    /* ---- profile ---- */
    'Edit Profil'            => 'Edit Profile',
    'Keamanan Akun'          => 'Account Security',
    'Total Pesanan'          => 'Total Orders',
    'Selesai'                => 'Completed',
    'Total Transaksi'        => 'Total Spent',
    'Kelengkapan profil'     => 'Profile completeness',
    'Kata Sandi Saat Ini'    => 'Current Password',
    'Kata Sandi Baru'        => 'New Password',
    'Ulangi Kata Sandi Baru' => 'Repeat New Password',
    'PERBARUI KATA SANDI'    => 'UPDATE PASSWORD',
    'SIMPAN PERUBAHAN'       => 'SAVE CHANGES',
    'Unggah Foto Baru'       => 'Upload New Photo',
    'Hapus avatar saat ini'  => 'Remove current avatar',
    'Nomor HP'               => 'Phone Number',
    'Jenis Kelamin'          => 'Gender',
    'Laki-laki'              => 'Male',
    'Perempuan'              => 'Female',
    'Lainnya'                => 'Other',
    'Pilih Jenis Kelamin'    => 'Select gender',

    /* ---- additional customer-facing pages (bulk pass) ---- */
    'Tentang' => 'About',
    'Selamat datang di' => 'Welcome to',
    'Dalam era digital yang semakin berkembang, perencanaan perjalanan kini menjadi lebih mudah dan praktis. TripVerse hadir sebagai solusi inovatif berbasis web yang dirancang untuk memberikan pengalaman perjalanan yang seamless, nyaman, dan terjangkau.' => 'In an increasingly digital era, travel planning is now easier and more practical. TripVerse is here as an innovative web-based solution designed to deliver a seamless, comfortable, and affordable travel experience.',
    'Sebagai platform pemesanan perjalanan, TripVerse memungkinkan pengguna untuk mencari dan memesan akomodasi hotel dengan cepat dan efisien. Kami menawarkan transparansi harga, rekomendasi perjalanan berbasis preferensi, manajemen pemesanan yang fleksibel, serta kemudahan dalam pembatalan dan perubahan jadwal.' => 'As a travel booking platform, TripVerse lets users search for and book hotel accommodations quickly and efficiently. We offer price transparency, preference-based travel recommendations, flexible booking management, and easy cancellations and schedule changes.',
    'Lebih dari sekadar platform reservasi, TripVerse adalah mitra perjalanan Anda. Dengan fitur unggulan seperti informasi harga yang jelas, kalender perjalanan, serta layanan pelanggan yang responsif, kami membantu Anda merancang perjalanan yang lebih terorganisir dan sesuai kebutuhan.' => 'More than just a reservation platform, TripVerse is your travel partner. With standout features like clear pricing information, a travel calendar, and responsive customer service, we help you plan trips that are more organized and tailored to your needs.',
    'Melalui TripVerse, kami berkomitmen untuk mendukung digitalisasi industri perjalanan dan meningkatkan kepuasan pengguna dalam mengelola perjalanan mereka. Bersama TripVerse, jelajahi dunia dengan lebih mudah, fleksibel, dan menyenangkan!' => 'Through TripVerse, we are committed to supporting the digitalization of the travel industry and improving user satisfaction in managing their trips. With TripVerse, explore the world more easily, flexibly, and enjoyably!',
    'Selengkapnya...' => 'Read more...',
    'Lebih Sedikit' => 'Show less',
    'Pegawai' => 'Staff',
    'Klien' => 'Clients',
    'Jelajahi Lebih Lanjut' => 'Explore More',
    'Tetap Nyaman, Bepergian dengan Kenangan!' => 'Stay Comfortable, Travel with Memories!',
    'Jelajahi Dunia, Ciptakan Cerita Anda!' => 'Explore the World, Create Your Story!',
    'Perjalanan Anda Dimulai di Sini!' => 'Your Journey Starts Here!',
    'Mulai dari' => 'Starting from',
    'Tempat Tidur' => 'Bed(s)',
    'Kamar Mandi' => 'Bathroom(s)',
    'Kamar nyaman dengan desain modern, cocok untuk keluarga kecil atau perjalanan bisnis.' => 'A comfortable room with a modern design, perfect for small families or business trips.',
    'Suite luas dengan fasilitas lengkap dan pemandangan kota yang menakjubkan.' => 'A spacious suite with complete facilities and a stunning city view.',
    'Kamar eksklusif dengan kenyamanan maksimal dan pelayanan bintang lima.' => 'An exclusive room with maximum comfort and five-star service.',
    'Pencarian & Pemesanan' => 'Search & Booking',
    'Cari hotel dengan mudah berdasarkan tanggal dan lokasi tujuan Anda.' => 'Easily search for hotels based on your dates and destination.',
    'Informasi Harga Transparan' => 'Transparent Pricing Information',
    'Harga yang ditampilkan sudah termasuk pajak & biaya layanan tanpa tambahan tersembunyi.' => 'The prices shown already include tax & service fees with no hidden extras.',
    'Manajemen Pemesanan' => 'Booking Management',
    'Akses riwayat pemesanan, cetak tiket, dan lihat detail perjalanan dengan mudah.' => 'Access your booking history, print tickets, and view trip details easily.',
    'Poin & Reward' => 'Points & Rewards',
    'Kumpulkan poin dari setiap pemesanan dan tukarkan dengan diskon eksklusif.' => 'Collect points from every booking and redeem them for exclusive discounts.',
    'Dapatkan bantuan cepat melalui WhatsApp untuk segala kendala perjalanan.' => 'Get quick help via WhatsApp for any travel issues.',
    'Pembatalan Fleksibel' => 'Flexible Cancellation',
    'Ubah atau batalkan pemesanan hotel Anda dengan mudah sesuai kebijakan yang berlaku.' => 'Change or cancel your hotel booking easily according to the applicable policy.',
    'Pernah dengar tentang Online Travel Agent, tapi masih bingung apa itu sebenarnya? 🤔✨ Jangan khawatir! Di video ini, kita akan membahas semuanya—mulai dari cara kerja, manfaat, hingga bagaimana OTA bisa membantu perjalananmu jadi lebih mudah dan praktis! 🎥✈️ Yuk, tonton sekarang dan temukan jawabannya! 🚀🌍' => 'Ever heard of an Online Travel Agent but still not sure what it actually is? Don\'t worry! In this video, we\'ll cover everything, from how it works and the benefits, to how an OTA can make your travels easier and more practical! Watch now and find out!',
    'Selamat Datang di' => 'Welcome to',
    'Karena kamu adalah pengguna baru, kamu mendapatkan' => 'Because you are a new user, you get',
    'DISKON KHUSUS' => 'SPECIAL DISCOUNT',
    'Kode:' => 'Code:',
    'Voucher berlaku HARI INI SAJA!' => 'Voucher valid TODAY ONLY!',
    'Voucher berlaku' => 'Voucher valid for',
    'hari lagi' => 'more day(s)',
    'Berlaku hingga:' => 'Valid until:',
    'Min. pembelian:' => 'Min. purchase:',
    'Maks. diskon:' => 'Max. discount:',
    'Cara pakai:' => 'How to use:',
    'Gunakan kode' => 'Use code',
    'saat checkout' => 'at checkout',
    'Voucher otomatis diterapkan untuk pemesanan pertama' => 'The voucher is automatically applied to your first booking',
    'Oke, Mengerti!' => 'Okay, Got It!',
    'Sekarang' => 'Now',
    'Diskon' => 'Discount',
    'berlaku' => 'valid for',
    'Akses ditolak! Halaman ini hanya untuk user.' => 'Access denied! This page is for customers only.',
    'Halo TripVerse, saya ingin bertanya tentang...' => 'Hi TripVerse, I would like to ask about...',
    'Terakhir dicari' => 'Recently searched',
    'Destinasi Populer (Jabodetabek)' => 'Popular Destinations (Greater Jakarta)',
    'Rekomendasi' => 'Recommended',
    'Hotel Lainnya' => 'Other Hotels',
    'Hotel di Kota Lain' => 'Hotels in Other Cities',
    'Restoran' => 'Restaurant',
    'Tidak ada hotel yang tersedia di kota ini.' => 'No hotels are available in this city.',
    'Lihat' => 'View',
    'Lihat Semua di' => 'View All in',
    'Apakah Anda yakin ingin menghapus semua riwayat hotel?' => 'Are you sure you want to delete all hotel history?',
    'Kontak Kami' => 'Contact Us',
    'Nama' => 'Name',
    'Subjek' => 'Subject',
    'Kritik & Pesan' => 'Feedback & Message',
    'Kirim Pesan' => 'Send Message',
    'Riwayat Pesanan' => 'Order History',
    'Riwayat Pesanan Hotel' => 'Hotel Booking History',
    'Daftar semua pemesanan hotel yang pernah Anda lakukan' => 'A list of all the hotel bookings you have made',
    'Semua' => 'All',
    'Belum Ada Riwayat Pesanan' => 'No Booking History Yet',
    'Tidak ada pesanan dengan status' => 'There are no bookings with the status',
    'Anda belum pernah melakukan pemesanan hotel melalui TripVerse' => 'You have not made any hotel bookings through TripVerse yet',
    'Waktu tersisa:' => 'Time remaining:',
    'menit' => 'minutes',
    'Tanggal Pesan:' => 'Order Date:',
    'Total' => 'Total',
    'Detail' => 'Details',
    'Bayar' => 'Pay',
    'Apakah Anda yakin ingin membatalkan pesanan ini?' => 'Are you sure you want to cancel this booking?',
    'Batalkan' => 'Cancel',
    'Hanya angka' => 'Numbers only',
    'Minimal 6 karakter' => 'Minimum 6 characters',
    'Nomor telepon harus minimal 10 digit!' => 'Phone number must be at least 10 digits.',
    'Semua kolom kata sandi wajib diisi.' => 'All password fields are required.',
    'Konfirmasi kata sandi tidak cocok.' => 'Password confirmation does not match.',
    'Kata sandi baru minimal 8 karakter.' => 'The new password must be at least 8 characters.',
    'Kata sandi baru harus memuat minimal satu huruf kapital.' => 'The new password must contain at least one uppercase letter.',
    'Kata sandi baru harus memuat minimal satu angka.' => 'The new password must contain at least one number.',
    'Kata sandi baru harus memuat minimal satu karakter spesial.' => 'The new password must contain at least one special character.',
    'Kata sandi baru harus berbeda dari kata sandi lama.' => 'The new password must be different from the old password.',
    'Kata sandi saat ini salah.' => 'The current password is incorrect.',
    'Kata sandi berhasil diperbarui.' => 'Password updated successfully.',
    'Gagal memperbarui kata sandi. Silakan coba lagi.' => 'Failed to update the password. Please try again.',
    'Ukuran file terlalu besar. Maksimal 5MB.' => 'The file is too large. Maximum 5MB.',
    'Tipe file tidak valid. Hanya JPG, PNG, GIF, WEBP yang diizinkan.' => 'Invalid file type. Only JPG, PNG, GIF, WEBP are allowed.',
    'Foto profil berhasil diupload.' => 'Profile photo uploaded successfully.',
    'Gagal mengupload foto.' => 'Failed to upload the photo.',
    'Ukuran file terlalu besar.' => 'The file is too large.',
    'File hanya terupload sebagian.' => 'The file was only partially uploaded.',
    'Folder temporary tidak ditemukan.' => 'Temporary folder not found.',
    'Gagal menulis file ke disk.' => 'Failed to write the file to disk.',
    'Upload dihentikan oleh extension.' => 'The upload was stopped by an extension.',
    'Error unknown saat upload file.' => 'Unknown error while uploading the file.',
    'Foto profil berhasil dihapus.' => 'Profile photo deleted successfully.',
    'Profil berhasil diperbarui!' => 'Profile updated successfully!',
    'Gagal memperbarui profil: ' => 'Failed to update profile: ',
    'Nama depan' => 'First name',
    'Nama belakang' => 'Last name',
    'Jenis kelamin' => 'Gender',
    'Foto profil' => 'Profile photo',
    'Profil Customer' => 'Customer Profile',
    'Member sejak' => 'Member since',
    'Lengkapi:' => 'Complete:',
    'Profil kamu sudah lengkap.' => 'Your profile is complete.',
    'Masukkan nama depan' => 'Enter your first name',
    'Masukkan nama belakang' => 'Enter your last name',
    'Masukkan alamat email' => 'Enter your email address',
    'Masukkan nomor handphone' => 'Enter your mobile number',
    'Gunakan kata sandi yang kuat dan tidak dipakai di layanan lain. Setelah diganti, kata sandi lama langsung tidak berlaku.' => 'Use a strong password that you do not use on other services. Once changed, the old password stops working immediately.',
    'Masukkan kata sandi saat ini' => 'Enter your current password',
    'Minimal 8 karakter' => 'At least 8 characters',
    'Ketik ulang kata sandi baru' => 'Retype the new password',
    'Kekuatan kata sandi' => 'Password strength',
    'Satu huruf kapital' => 'One uppercase letter',
    'Satu angka' => 'One number',
    'Satu karakter spesial' => 'One special character',
    'Konfirmasi cocok' => 'Confirmation matches',
    'Preferensi tampilan akun kamu. Untuk mengubah kata sandi, buka' => 'Your account display preferences. To change your password, open',
    'Ubah bahasa TripVerse kapan saja lewat pengalih ID/EN di bagian atas halaman.' => 'Change the TripVerse language anytime using the ID/EN switcher at the top of the page.',
    'Negara atau Wilayah' => 'Country or Region',
    'Pemesanan hotel tersedia untuk wilayah Jabodetabek.' => 'Hotel booking is available for the Greater Jakarta (Jabodetabek) area.',
    'Ganti kata sandi kamu' => 'Change your password',
    'Lihat semua pemesanan kamu' => 'View all your bookings',
    'Halaman ini sedang dalam pengembangan. Fitur' => 'This page is under development. The',
    'akan segera tersedia.' => 'feature will be available soon.',
    'Apakah Anda yakin ingin menghapus foto profil?' => 'Are you sure you want to delete your profile photo?',
    'Akun Saya' => 'My Account',
    'Kelola dan lihat riwayat pembelian hotel Anda' => 'Manage and view your hotel purchase history',
    '90 Hari Terakhir' => 'Last 90 Days',
    '30 Hari Terakhir' => 'Last 30 Days',
    'Bulan Ini' => 'This Month',
    'Bulan Lalu' => 'Last Month',
    'Tahun Ini' => 'This Year',
    'Tanggal Custom' => 'Custom Date',
    's/d' => 'to',
    'Terapkan Filter' => 'Apply Filter',
    'Reset' => 'Reset',
    'Tidak ada pembelian dalam' => 'No purchases in',
    '90 hari terakhir' => 'the last 90 days',
    '30 hari terakhir' => 'the last 30 days',
    'bulan ini' => 'this month',
    'bulan lalu' => 'last month',
    'tahun ini' => 'this year',
    'rentang tanggal yang dipilih' => 'the selected date range',
    'periode yang dipilih' => 'the selected period',
    'Jika Anda pernah melakukan pembelian sebelumnya, silakan gunakan Filter untuk melihatnya.' => 'If you have made purchases before, please use the Filter to view them.',
    'BARU' => 'NEW',
    'Tipe Kamar' => 'Room Type',
    'Jumlah Kamar' => 'Number of Rooms',
    'Status Booking' => 'Booking Status',
    'Transaksi:' => 'Transaction:',
    'Detail Hotel' => 'Hotel Details',
    'Tersedia kamar' => 'Rooms available',
    'Tentang Hotel Ini' => 'About This Hotel',
    'Fasilitas Hotel' => 'Hotel Facilities',
    'Lokasi Hotel' => 'Hotel Location',
    'Peta Lokasi' => 'Location Map',
    'Informasi Peta Tidak Tersedia' => 'Map Information Not Available',
    'Silakan hubungi hotel untuk petunjuk arah' => 'Please contact the hotel for directions',
    'Pilihan Kamar' => 'Room Options',
    'Orang' => 'People',
    'Sarapan' => 'Breakfast',
    'Ketersediaan:' => 'Availability:',
    'kamar' => 'room(s)',
    'Maaf, tidak ada kamar yang tersedia untuk periode ini.' => 'Sorry, no rooms are available for this period.',
    'Ringkasan Pemesanan' => 'Booking Summary',
    'Detail Tamu' => 'Guest Details',
    'Tamu:' => 'Guests:',
    'Kembali ke Daftar' => 'Back to List',
    'Layanan Tambahan' => 'Additional Services',
    'Promo Akan Digunakan!' => 'Promo Will Be Applied!',
    'Promo akan digunakan pada pesanan ini senilai' => 'A promo will be applied to this order worth',
    'Pilih Layanan Tambahan' => 'Choose Additional Services',
    'Pilih layanan tambahan yang Anda butuhkan. Semua layanan bersifat opsional.' => 'Choose the additional services you need. All services are optional.',
    'Makanan' => 'Food',
    'Transportasi' => 'Transportation',
    'Tambah' => 'Add',
    'Lanjutkan tanpa layanan tambahan?' => 'Continue without additional services?',
    'Lanjutkan ke pembayaran?' => 'Continue to payment?',
    'Tipe Kamar:' => 'Room Type:',
    'Jumlah Kamar:' => 'Number of Rooms:',
    'Harga Kamar' => 'Room Price',
    'Harga Kamar Setelah Diskon' => 'Room Price After Discount',
    'Hapus' => 'Remove',
    'Belum ada layanan tambahan' => 'No additional services yet',
    'Total Layanan Tambahan' => 'Total Additional Services',
    'Hemat' => 'Save',
    'Batal' => 'Cancel',
    'Ya, Lanjutkan' => 'Yes, Continue',
    'Terjadi kesalahan: ' => 'An error occurred: ',
    'Pembayaran QRIS' => 'QRIS Payment',
    'Pemesanan' => 'Booking',
    'Waktu pembayaran telah habis. Pemesanan otomatis dibatalkan.' => 'The payment time has expired. The booking was automatically cancelled.',
    'Perhatian:' => 'Attention:',
    'Jika Anda membatalkan pemesanan, kuota diskon' => 'If you cancel the booking, the discount quota for',
    'akan otomatis dikembalikan ke sistem.' => 'will automatically be returned to the system.',
    'Bayar dengan QRIS' => 'Pay with QRIS',
    'Silakan scan kode QR di bawah menggunakan aplikasi mobile banking atau e-wallet Anda untuk menyelesaikan pembayaran.' => 'Please scan the QR code below using your mobile banking or e-wallet app to complete the payment.',
    'Kode QRIS' => 'QRIS Code',
    'ID Pemesanan:' => 'Booking ID:',
    'Petunjuk Pembayaran:' => 'Payment Instructions:',
    'Buka aplikasi mobile banking atau e-wallet Anda yang mendukung QRIS' => 'Open your mobile banking or e-wallet app that supports QRIS',
    'Pilih menu "Scan QR" atau "Bayar dengan QRIS"' => 'Select the "Scan QR" or "Pay with QRIS" menu',
    'Arahkan kamera Anda ke kode QR di atas' => 'Point your camera at the QR code above',
    'Masukkan jumlah pembayaran jika diminta' => 'Enter the payment amount if asked',
    'Konfirmasi pembayaran dan masukkan PIN/Password Anda' => 'Confirm the payment and enter your PIN/Password',
    'Tunggu notifikasi pembayaran berhasil' => 'Wait for the payment success notification',
    'Pemesanan Anda akan otomatis dibatalkan jika pembayaran tidak selesai dalam 2 menit.' => 'Your booking will be automatically cancelled if payment is not completed within 2 minutes.',
    'Pajak & Layanan:' => 'Tax & Service:',
    'Termasuk' => 'Included',
    'Kuota diskon' => 'The discount quota for',
    'Apakah Anda sudah menyelesaikan pembayaran?' => 'Have you completed the payment?',
    'Pemesanan Hotel' => 'Hotel Booking',
    'Selamat! Diskon Pengguna Baru 25% Telah Aktif' => 'Congratulations! Your 25% New User Discount Is Active',
    'Anda mendapatkan diskon khusus untuk pengguna baru TripVerse. Voucher ini akan hangus dalam:' => 'You got a special discount for new TripVerse users. This voucher expires in:',
    'hari' => 'day(s)',
    'Kurang dari 1 hari' => 'Less than 1 day',
    'kurang dari 1 hari' => 'less than 1 day',
    'Kode Promo' => 'Promo Code',
    'Masukkan kode promo untuk mendapatkan diskon spesial' => 'Enter a promo code to get a special discount',
    'Diskon Otomatis' => 'Automatic Discount',
    'Min. belanja:' => 'Min. spend:',
    'Masukkan kode promo' => 'Enter promo code',
    'Terapkan' => 'Apply',
    'Diskon NEWUSER hanya berlaku otomatis untuk pengguna baru' => 'The NEWUSER discount only applies automatically for new users',
    'Kode promo berhasil diterapkan! Anda hemat' => 'Promo code applied successfully! You saved',
    'Kode promo tidak valid atau tidak memenuhi syarat' => 'The promo code is invalid or does not meet the requirements',
    'Data pemesan tidak valid. Silakan periksa kembali.' => 'The booker data is invalid. Please check again.',
    'Gagal memproses data pemesanan: ' => 'Failed to process the booking data: ',
    'Kode promo hanya bisa digunakan sekali dan tidak dapat digabungkan dengan promo lainnya.' => 'The promo code can only be used once and cannot be combined with other promos.',
    'Minimal pembelian:' => 'Minimum purchase:',
    'Detail Pemesan' => 'Booker Details',
    'Lengkapi detailnya dengan datamu. Ini akan dikirim ke hotel untuk keperluan pemesanan.' => 'Fill in the details with your data. This will be sent to the hotel for booking purposes.',
    'Tuan' => 'Mr.',
    'Nyonya' => 'Mrs.',
    'Nona' => 'Ms.',
    'Nama Lengkap Sesuai Identitas' => 'Full Name as per ID',
    'Nomor telepon aktif untuk konfirmasi pemesanan.' => 'An active phone number for booking confirmation.',
    'Alamat Email' => 'Email Address',
    'Konfirmasi pemesanan akan dikirim ke email ini.' => 'The booking confirmation will be sent to this email.',
    'Malam' => 'Night(s)',
    'Tamu' => 'Guests',
    'WiFi Gratis' => 'Free WiFi',
    'Kamar Non-smoking' => 'Non-smoking Room',
    'Ada Permintaan Khusus?' => 'Have a Special Request?',
    'Permintaan Khusus' => 'Special Request',
    'Pemenuhan permintaan tergantung pada ketersediaan dan mungkin dikenakan biaya tambahan saat check-in.' => 'Fulfillment of requests depends on availability and may incur additional charges at check-in.',
    'Lantai Atas' => 'Higher Floor',
    'Kamar dengan Pintu Terhubung' => 'Connecting Room',
    'Waktu Check-in Khusus' => 'Special Check-in Time',
    'Waktu Check-out Khusus' => 'Special Check-out Time',
    'Isi Permintaan Lain' => 'Other Requests',
    'Tulis permintaan khusus lainnya di sini...' => 'Write any other special requests here...',
    'Simpan' => 'Save',
    'Catatan Khusus (Opsional)' => 'Special Notes (Optional)',
    'Masukkan catatan khusus jika ada' => 'Enter any special notes',
    'Pajak & Layanan' => 'Tax & Service',
    'Diskon Pengguna Baru Aktif!' => 'New User Discount Active!',
    'Voucher ini akan hangus dalam' => 'This voucher expires in',
    'Permintaan khusus telah disimpan!' => 'Your special request has been saved!',
    'Harap lengkapi semua data pemesan yang wajib diisi.' => 'Please fill in all required booker information.',
    'Format email tidak valid.' => 'The email format is invalid.',
    'Hotel Terakhir Dilihat' => 'Recently Viewed Hotels',
    'Hapus semua riwayat hotel?' => 'Delete all hotel history?',
    'Hapus semua' => 'Delete all',
    'Belum ada riwayat hotel' => 'No hotel history yet',
    'Hapus dari riwayat' => 'Remove from history',
    'Hapus hotel ini dari riwayat?' => 'Remove this hotel from history?',
    'Riwayat Pencarian' => 'Search History',
    'Hapus semua riwayat?' => 'Delete all history?',
    'Hapus Semua' => 'Delete All',
    'Belum ada riwayat pencarian.' => 'No search history yet.',
    'Belum ada riwayat hotel.' => 'No hotel history yet.',
    'Konfirmasi Berhasil' => 'Confirmation Successful',
    'Pembayaran Berhasil!' => 'Payment Successful!',
    'Terima kasih telah memesan di TripVerse. Detail pemesanan telah dikirim ke email Anda.' => 'Thank you for booking with TripVerse. Your booking details have been sent to your email.',
    'Hotel:' => 'Hotel:',
    'Total:' => 'Total:',
    'Pesan Hotel Lain' => 'Book Another Hotel',
    'Booking tidak ditemukan atau Anda tidak memiliki akses' => 'Booking not found or you do not have access',
    'Kembali ke Riwayat' => 'Back to History',
    'Kode Booking:' => 'Booking Code:',
    'Kapasitas:' => 'Capacity:',
    'orang' => 'people',
    'No. HP:' => 'Phone:',
    'Detail Pembayaran' => 'Payment Details',
    'ID Transaksi:' => 'Transaction ID:',
    'Tanggal Transaksi:' => 'Transaction Date:',
    'Metode Pembayaran:' => 'Payment Method:',
    'Total Pembayaran:' => 'Total Payment:',
    'Deskripsi Kamar' => 'Room Description',
    'Ukuran Kamar:' => 'Room Size:',
    'Kamar Tersedia:' => 'Rooms Available:',
    'Lihat Invoice' => 'View Invoice',
    'Batalkan Pesanan' => 'Cancel Booking',
    'Bayar Sekarang' => 'Pay Now',
    'Cari Hotel Lain' => 'Search Other Hotels',
    'Payment Confirmation' => 'Payment Confirmation',
    'Gagal mengirim pesan' => 'Failed to send message',
    'Transaksi tidak ditemukan atau sudah dikirim' => 'Transaction not found or already sent',
    'Konfirmasi Pembayaran TripVerse' => 'TripVerse Payment Confirmation',
    'Hari Ini' => 'Today',
    'Kirim Semua Belum Dikirim' => 'Send All Unsent',
    'Status WA' => 'WA Status',
    'Aksi' => 'Action',
    'Sudah Dikirim' => 'Sent',
    'Belum Dikirim' => 'Not Sent',
    'Tidak ada transaksi hari ini.' => 'No transactions today.',
    'Mengirim...' => 'Sending...',
    'Gagal:' => 'Failed:',
    'Mengirim semua...' => 'Sending all...',
    'Berhasil mengirim' => 'Successfully sent',
    'pesan.' => 'message(s).',
    'Gagal mengirim semua pesan' => 'Failed to send all messages',
    'Pesan berhasil dikirim ke' => 'Message successfully sent to',
    'Gagal mengirim pesan ke' => 'Failed to send message to',
    'Data tidak lengkap, pesan tidak dikirim.' => 'Incomplete data, message not sent.',
    'Tidak ada pesan yang dikirim.' => 'No messages were sent.',
    'Manual Reminder Check-In' => 'Manual Check-In Reminder',
    'Pengingat Check-In TripVerse' => 'TripVerse Check-In Reminder',
    'Besok' => 'Tomorrow',
    'Tidak ada pelanggan yang check-in besok.' => 'No customers are checking in tomorrow.',
    'Pelanggan' => 'Customer',
    'Halo' => 'Hello',
    'Pembayaran untuk Booking' => 'Payment for Booking',
    'telah' => 'has been',
    'BERHASIL dikonfirmasi' => 'SUCCESSFULLY confirmed',
    'Kota' => 'City',
    'Kami sedang membuat e-ticket Anda...' => 'We are generating your e-ticket...',
    'E-Ticket Pembayaran' => 'Payment E-Ticket',
    'Terima kasih telah memesan melalui TripVerse' => 'Thank you for booking through TripVerse',
    'Detail Transaksi' => 'Transaction Details',
    'Tanggal Pembayaran:' => 'Payment Date:',
    'Status:' => 'Status:',
    'Nama:' => 'Name:',
    'Email:' => 'Email:',
    'Rincian Pembayaran' => 'Payment Breakdown',
    'Informasi Penting:' => 'Important Information:',
    'Tunjukkan e-ticket dan kode booking saat check-in di hotel.' => 'Show your e-ticket and booking code when checking in at the hotel.',
    'Pembatalan minimal 24 jam sebelum waktu check-in.' => 'Cancellations must be made at least 24 hours before check-in.',
    'E-ticket ini juga telah dikirim ke WhatsApp Anda.' => 'This e-ticket has also been sent to your WhatsApp.',
    'Berikut E-Ticket Anda untuk Booking ID' => 'Here is your E-Ticket for Booking ID',
    'Terima kasih telah menggunakan TripVerse' => 'Thank you for using TripVerse',
    'Booking tidak ditemukan atau tidak memiliki akses.' => 'Booking not found or you do not have access.',
    'Nama Hotel' => 'Hotel Name',
    'Konfirmasi Pembayaran' => 'Payment Confirmation',
    'ID Transaksi Hotel:' => 'Hotel Transaction ID:',
    'Detail Kamar' => 'Room Details',
    'Durasi Menginap:' => 'Length of Stay:',
    'Diskon Berhasil Diterapkan' => 'Discount Successfully Applied',
    'Fasilitas Ekstra yang Dipilih' => 'Selected Extra Facilities',
    'Jumlah:' => 'Quantity:',
    'Subtotal:' => 'Subtotal:',
    'Tunjukkan kode booking dan identitas saat check-in di hotel' => 'Show your booking code and ID when checking in at the hotel',
    'Pembatalan atau perubahan dapat dilakukan minimal 24 jam sebelum check-in' => 'Cancellations or changes can be made at least 24 hours before check-in',
    'E-ticket telah dikirim ke email' => 'The e-ticket has been sent to the email',
    'Hubungi customer service jika ada pertanyaan' => 'Contact customer service if you have any questions',
    'Fasilitas ekstra akan disiapkan oleh hotel sesuai dengan pilihan Anda' => 'Extra facilities will be prepared by the hotel according to your selection',
    'Diskon telah berhasil diterapkan pada pemesanan Anda' => 'The discount has been successfully applied to your booking',
    'Lihat Riwayat' => 'View History',
    'Unduh Bukti Pembayaran' => 'Download Payment Receipt',
    'Membuat PDF...' => 'Creating PDF...',
    'Terjadi kesalahan saat membuat PDF. Silakan coba lagi.' => 'An error occurred while creating the PDF. Please try again.',
    'Lupa Password' => 'Forgot Password',
    'Masukkan nomor WhatsApp Anda' => 'Enter your WhatsApp number',
    'Masukkan email Anda' => 'Enter your email',
    'Silakan masukkan email' => 'Please enter your email',
    'Minta OTP' => 'Request OTP',
    'Ingat password Anda?' => 'Remember password?',
    'Verifikasi OTP' => 'Verify OTP',
    'Masukkan 6 digit OTP yang dikirim ke WhatsApp' => 'Enter the 6-digit OTP sent to WhatsApp',
    'Masukkan 6 digit OTP yang dikirim ke email Anda' => 'Enter the 6-digit OTP sent to your email',
    'Tidak menerima kode?' => 'Didn\'t receive code?',
    'Kirim Ulang OTP' => 'Resend OTP',
    'Atur Ulang Password' => 'Reset Password',
    'Buat password baru' => 'Create a new password',
    'Password Baru' => 'New Password',
    'Password harus mengandung:' => 'Password must contain:',
    'Minimal satu huruf kapital' => 'At least one uppercase letter',
    'Minimal satu angka' => 'At least one number',
    'Simpan Password' => 'Save Password',
    'Silakan masukkan nomor telepon' => 'Please enter phone number',
    'OTP berhasil dikirim!' => 'OTP sent successfully!',
    'Gagal mengirim OTP. Server merespons:' => 'Failed to send OTP. Server returned:',
    'Kesalahan jaringan:' => 'Network error:',
    'Silakan masukkan OTP lengkap' => 'Please enter complete OTP',
    'Memverifikasi...' => 'Verifying...',
    'OTP berhasil diverifikasi!' => 'OTP verified successfully!',
    'OTP telah kedaluwarsa. Silakan minta yang baru.' => 'OTP expired. Please request a new one.',
    'OTP salah. Silakan coba lagi.' => 'Incorrect OTP. Please try again.',
    'Permintaan tidak valid. Silakan ulangi proses.' => 'Invalid request. Please restart the process.',
    'Verifikasi gagal. Silakan coba lagi.' => 'Verification failed. Please try again.',
    'Kesalahan jaringan. Silakan periksa koneksi Anda.' => 'Network error. Please check your connection.',
    'Password tidak cocok' => 'Passwords do not match',
    'Password berhasil diperbarui! Mengalihkan...' => 'Password updated! Redirecting...',
    'Gagal memperbarui password' => 'Failed to update password',
    'Akun supplier Anda telah ditolak. Silakan hubungi administrator.' => 'Your supplier account has been rejected. Please contact administrator.',
    'Akun supplier Anda sedang menunggu persetujuan. Anda mungkin memiliki akses terbatas hingga disetujui.' => 'Your supplier account is pending approval. You may have limited access until approved.',
    'Email atau password salah!' => 'Invalid email or password!',
    'Pengguna tidak ditemukan!' => 'User not found!',
    'Daftar & Masuk' => 'Register & Login',
    'Daftar Sebagai Customer' => 'Register as Customer',
    'Nomor harus diawali +62' => 'Number must start with +62',
    'Kami mengirim kode 6 digit ke WhatsApp Anda.' => 'We sent a 6-digit code to your WhatsApp.',
    'Bergabunglah sebagai mitra bisnis profesional kami' => 'Join as our professional business partner',
    'Password tidak cocok!' => 'Passwords do not match!',
    'Password tidak memenuhi semua persyaratan!' => 'Password does not meet all requirements!',
    'Nomor telepon wajib diisi.' => 'Phone number required.',
    'OTP terkirim ke WhatsApp!' => 'OTP sent to WhatsApp!',
    'OTP valid! Membuat akun...' => 'OTP valid! Creating account...',
    'OTP kedaluwarsa. Silakan minta lagi.' => 'OTP expired. Request again.',
    'OTP salah!' => 'Wrong OTP!',
    'selamat datang di TripVerse' => 'welcome to TripVerse',
    'Hasil Pencarian Hotel' => 'Hotel Search Results',
    'Hasil Pencarian' => 'Search Results',
    'Hasil Pencarian Hotel di' => 'Hotel Search Results for',
    'Filter Hotel' => 'Filter Hotels',
    'Harga Maksimal' => 'Maximum Price',
    'Maks:' => 'Max:',
    'Fasilitas' => 'Facilities',
    'Wi-Fi Gratis' => 'Free Wi-Fi',
    'Kolam Renang' => 'Swimming Pool',
    'Reset Filter' => 'Reset Filter',
    'Pilih Kamar' => 'Choose Room',
    'Maaf, tidak ada hotel yang tersedia di' => 'Sorry, no hotels are available in',
    'Coba cari dengan kriteria yang berbeda atau pilih kota lain.' => 'Try searching with different criteria or choose another city.',
    'Kembali ke Pencarian Hotel' => 'Back to Hotel Search',
    'Silakan masukkan destinasi' => 'Please enter a destination',
    'Silakan pilih tanggal check-in dan check-out' => 'Please select check-in and check-out dates',
    'Maksimal 10 untuk setiap kategori' => 'Maximum 10 for each category',
    'Jumlah kamar tidak boleh lebih dari jumlah dewasa' => 'The number of rooms cannot exceed the number of adults',
    'Pilih Tamu' => 'Select Guests',
    'Tanggal check-out harus setelah check-in' => 'Check-out date must be after check-in',
    'Tidak ada hotel yang sesuai dengan filter' => 'No hotels match the filter',

    /* ---- extra_services.php: booking-processing exceptions ---- */
    'Gagal update kuota diskon' => 'Failed to update the discount quota',
    'Gagal mencatat penggunaan diskon' => 'Failed to record discount usage',
    'Gagal menyimpan booking: ' => 'Failed to save booking: ',
    'Gagal menyimpan fasilitas: ' => 'Failed to save facilities: ',
    'Gagal update ketersediaan kamar: ' => 'Failed to update room availability: ',
    'Gagal menyimpan transaksi: ' => 'Failed to save transaction: ',
    'Gagal menyimpan transaksi hotel: ' => 'Failed to save hotel transaction: ',
    'Lanjutkan?' => 'Continue?',
    'Parameter pemesanan tidak valid' => 'Invalid booking parameters',
    'Format tanggal tidak valid: ' => 'Invalid date format: ',
    'Hotel tidak ditemukan' => 'Hotel not found',
    'Kamar tidak tersedia atau stok habis. Tersedia:' => 'The room is unavailable or out of stock. Available:',
    'Diskon tidak valid atau kuota habis' => 'The discount is invalid or its quota has been used up',

    /* ---- home.php: hero carousel ---- */
    'Hotel Pilihan Untuk Setiap Perjalanan' => 'Hand-Picked Hotels For Every Trip',
    'Kenyamanan yang Menyambut Anda' => 'Comfort That Welcomes You',
    'Lebih dari Sekadar Hotel' => 'More Than Just Hotels',
    'Petualangan di Udara, Segera Hadir' => 'Adventures in the Sky, Coming Soon',

    /* ---- flights.php: coming-soon placeholder ---- */
    'Segera Hadir' => 'Coming Soon',
    'Fitur pemesanan tiket pesawat sedang kami siapkan supaya perjalananmu makin lengkap, dari hotel sampai penerbangan dalam satu platform.'
        => "We're putting the finishing touches on flight booking, so your whole trip \u{2014} hotel and flights \u{2014} will fit in one platform.",

    /* ---- admin panel: shared sidebar chrome ---- */
    'Dasbor Admin'            => 'Admin Dashboard',
    'Kelola Akun'             => 'Manage Account',
    'Keluar'                  => 'Logout',
    'Ringkasan Eksekutif'     => 'Executive Overview',
    'Manajemen Supplier'      => 'Supplier Management',
    'Manajemen Promo'         => 'Promo Management',
    'Monitoring Performa'     => 'Performance Monitoring',
    'Statistik Performa'      => 'Performance Statistics',
    'Tren Booking'            => 'Booking Trends',
    'Analisis Statistik'      => 'Statistical Analysis',
    'Statistik Pendapatan'    => 'Revenue Statistics',
    'Statistik Okupansi'      => 'Occupancy Statistics',
    'Statistik ALOS'          => 'ALOS Statistics',
    'Statistik Pelanggan'     => 'Customer Statistics',

    /* ---- admin panel: owner/supplier operational sidebar ---- */
    /* ---- admin panel: dashboard.php content ---- */
    'Visualisasi Data - TripVerse Admin' => 'Data Visualization - TripVerse Admin',
    'Total Pendapatan'          => 'Total Revenue',
    'Aktif'                      => 'Active',
    'Booking Selesai'           => 'Completed Bookings',
    'Rata-rata Lama Menginap'  => 'Avg. Length of Stay',
    'Tingkat Pembatalan'        => 'Cancellation Rate',
    'Perlu Perhatian'           => 'Needs Attention',
    'Hotel Aktif'                => 'Active Hotels',
    'Operasional'                => 'Operational',
    'Analisis Tren Booking & Pendapatan' => 'Booking Trends & Revenue Analysis',
    'Tren Booking Bulanan'      => 'Monthly Booking Trends',
    'Pendapatan Bulanan'        => 'Monthly Revenue',
    'Analisis Ketersediaan Kamar' => 'Room Availability Analysis',
    'Stok Kamar Keseluruhan'    => 'Overall Room Stock',
    'Ketersediaan Kamar per Tipe' => 'Room Availability by Type',
    'Hotel dengan Performa Terbaik' => 'Top Performing Hotels',
    'Nama Hotel'                 => 'Hotel Name',
    'Total Booking'              => 'Total Bookings',
    'Pendapatan'                  => 'Revenue',
    'Tanggal Booking'            => 'Booking Date',
    'Menunggu'                    => 'Pending',
    'Memuat detail booking...'  => 'Loading booking details...',
    'Informasi Pelanggan'       => 'Customer Information',
    'Nama Pelanggan'             => 'Customer Name',
    'Telepon'                     => 'Phone',
    'Harga Total'                 => 'Total Price',
    'Metode Pembayaran'         => 'Payment Method',
    'ID Booking'                  => 'Booking ID',
    'Tanggal Check-in'           => 'Check-in Date',
    'Tanggal Check-out'          => 'Check-out Date',
    'Harga Total (IDR)'         => 'Total Price (IDR)',
    'Hotel (Hanya Baca)'         => 'Hotel (Read-only)',
    'Tipe Kamar (Hanya Baca)'   => 'Room Type (Read-only)',
    'Permintaan Khusus / Catatan' => 'Special Requests / Notes',
    'Ada permintaan khusus atau catatan...' => 'Any special requests or notes...',
    'Rata-rata Menginap'        => 'Avg. Stay',
    'Belum ada data performa hotel' => 'No hotel performance data available',
    'Daftar Booking'             => 'Booking List',
    'Cari hotel atau pelanggan...' => 'Search hotel or customer...',
    'Semua Status'               => 'All Status',
    'Semua Bulan'                => 'All Months',
    'Semua Tahun'                => 'All Years',
    'Reset Filter'                => 'Clear All',
    'Tidak Ada Booking'         => 'No Bookings Found',
    'Belum ada booking dalam sistem.' => 'There are no bookings in the system.',
    'Detail Booking'             => 'Booking Details',
    'Tutup'                       => 'Close',
    'Simpan Perubahan'          => 'Save Changes',
    'Edit Booking'                => 'Edit Booking',
    'Hari'                        => 'Days',

    /* ---- admin panel: supplier_approvals.php content ---- */
    'Manajemen Persetujuan Supplier' => 'Supplier Approval Management',
    'Tinjau dan kelola permintaan pendaftaran supplier' => 'Review and manage supplier registration requests',
    'Permintaan Tertunda'       => 'Pending Requests',
    'Menunggu tinjauan'         => 'Awaiting review',
    'Disetujui'                   => 'Approved',
    'Supplier aktif'             => 'Active suppliers',
    'Ditolak'                     => 'Rejected',
    'Aplikasi ditolak'          => 'Declined applications',
    'Tingkat Persetujuan'      => 'Approval Rate',
    'Kelola Owner'                => 'Manage Owners',
    'Tidak Ada Permintaan Tertunda' => 'No Pending Requests',
    'Semua permintaan supplier telah diproses' => 'All supplier requests have been processed',
    'Belum Ada Supplier Disetujui' => 'No Approved Suppliers',
    'Belum ada supplier yang disetujui' => 'No suppliers have been approved yet',
    'Tidak Ada Supplier Ditolak' => 'No Rejected Suppliers',
    'Belum ada supplier yang ditolak' => 'No suppliers have been rejected',
    'Setujui'                     => 'Approve',
    'Tolak'                        => 'Reject',
    'Disetujui oleh:'            => 'Approved by:',
    'Disetujui pada:'            => 'Approved on:',
    'Ditolak oleh:'               => 'Rejected by:',
    'Ditolak pada:'               => 'Rejected on:',
    'Tidak ada email'            => 'No email',
    'Tidak ada telepon'          => 'No phone',
    'Belum ditinjau'             => 'Not reviewed yet',
    'Supplier Tidak Diketahui'  => 'Unknown Supplier',
    'Belum Ditinjau'             => 'Not Reviewed',
    'Menunggu Peninjauan'       => 'Pending Review',
    /* ---- admin panel: promo_management.php content ---- */
    /* ---- admin panel: market_analysis.php content ---- */
    'Analisis Tren Pemesanan Hotel - TripVerse' => 'Hotel Booking Trend Analysis - TripVerse',
    'Analisis Tren Pemesanan (6 Bulan Terakhir)' => 'Booking Trend Analysis (Last 6 Months)',
    'Analisis Pangsa Pasar'      => 'Market Share Analysis',
    'Performa berdasarkan Kota' => 'Performance by City',
    'Performa Hotel Detail'      => 'Detailed Hotel Performance',
    'Bulan'                        => 'Month',
    'Booking Berhasil'           => 'Successful Bookings',

    /* ---- admin panel: occupancy_analysis.php content ---- */
    'Dasbor Statistik Okupansi'  => 'Occupancy Statistics Dashboard',
    'Performa Okupansi Hotel'    => 'Hotel Occupancy Performance',
    'Tren Okupansi'                => 'Occupancy Trends',
    'Hotel & Kamar'                => 'Hotel & Rooms',

    /* ---- admin panel: alos_analysis.php content ---- */
    'Analisis ALOS - Analisis Rata-rata Lama Menginap' => 'ALOS Analysis - Analisis Rata-rata Lama Menginap',
    'Rata-rata ALOS'              => 'Average ALOS',
    'Total Malam'                  => 'Total Nights',
    'Menginap Tersingkat'         => 'Shortest Stay',
    'Menginap Terlama'            => 'Longest Stay',
    'Pendapatan per Malam'       => 'Revenue per Malam',
    'Tren ALOS Bulanan'           => 'Monthly ALOS Trend',
    'Analisis Distribusi ALOS'   => 'ALOS Distribution Analysis',
    'Analisis ALOS per Hotel'    => 'ALOS Analysis by Hotel',
    'Analisis ALOS per Tipe Kamar' => 'ALOS Analysis by Room Type',
    'Korelasi ALOS vs Pendapatan' => 'ALOS vs Revenue Correlation',
    'Kinerja Segmen ALOS'         => 'ALOS Segment Performance',

    /* ---- admin panel: customerdss.php content ---- */
    'Sistem Pendukung Keputusan Pelanggan' => 'Customer Decision Support System',
    'Total Pelanggan'             => 'Total Customers',
    'Pelanggan Aktif'             => 'Active Customers',
    'Baru Minggu Ini'             => 'New This Week',
    'Rata-rata Booking/Pelanggan' => 'Avg. Bookings/Customer',
    'Rata-rata Pengeluaran/Pelanggan' => 'Avg. Spent/Customer',
    'Pertumbuhan & Demografi Pelanggan' => 'Customer Growth & Demographics',
    'Pelanggan dengan Pengeluaran Tertinggi' => 'Top Spending Customers',
    'Manajemen Pelanggan'         => 'Customer Management',
    'Detail Pelanggan'            => 'Customer Details',
    'Edit Pelanggan'               => 'Edit Customer',
    'Konfirmasi Hapus'            => 'Confirm Delete',

    /* ---- supplier panel: owner_dashboard.php content ---- */
    'Selamat datang kembali,'    => 'Welcome back,',
    'Kelola hotel Anda dan pantau bisnis Anda' => 'Manage your hotels and track your business',
    'Tambah Hotel'                 => 'Add Hotel',
    'Total Hotel'                  => 'Total Hotels',
    'Properti Aktif'              => 'Active Properties',
    'Total Kamar'                  => 'Total Rooms',
    'Unit Tersedia'               => 'Available Units',
    'Semua Booking'               => 'All Time Bookings',
    'Pendapatan Bersih'           => 'Net Revenue',
    'Setelah potongan biaya admin 5%' => 'After 5% admin fee deduction',
    'Hanya booking selesai'      => 'Completed bookings only',
    'Hotel Berperforma Terbaik'  => 'Top Performing Hotels',
    'Pilih Hotel'                  => 'Select a Hotel',
    'Klik hotel dari Hotel Berperforma Terbaik untuk melihat data okupansi' => 'Click on a hotel from Top Performing Hotels to view occupancy data',
    'Hotel Terbaru'                => 'Recent Hotels',
    'Booking Terbaru'             => 'Recent Bookings',

    /* ---- supplier panel: hotel_manage.php content ---- */
    'Manajemen Hotel'             => 'Hotel Management',
    'Kelola hotel dan properti Anda' => 'Manage your hotels and properties',
    'Hotel Saya'                   => 'My Hotels',
    'Belum ada hotel'             => 'No hotels yet',
    'Mulai dengan menambahkan hotel pertama Anda' => 'Start by adding your first hotel',
    'Tambah Hotel Pertama'       => 'Add First Hotel',

    /* ---- supplier panel: room_management.php content ---- */
    'Manajemen Kamar'             => 'Room Management',
    'Kelola tipe kamar dan harga untuk hotel Anda' => 'Manage room types and pricing for your hotels',
    'Tambah Tipe Kamar'          => 'Add Room Type',
    'Belum ada kamar'             => 'No rooms found',
    'Tambahkan kamar pertama Anda untuk memulai' => 'Add your first room to get started',
    'Tambah Kamar'                 => 'Add Room',

    /* ---- supplier panel: booking_management.php content ---- */
    'Manajemen Booking'           => 'Booking Management',
    'Kelola booking dan reservasi pelanggan' => 'Manage customer bookings and reservations',
    'Update Status Booking'      => 'Update Booking Status',

    /* ---- supplier panel: extra_facilities_manage.php content ---- */
    'Kelola Fasilitas Tambahan'  => 'Manage Extra Facilities',
    'Atur fasilitas berbayar untuk setiap hotel Anda' => 'Set up paid facilities for each of your hotels',
    'Tidak ada fasilitas tambahan tersedia' => 'No extra facilities available',

    /* ---- admin/supplier panel: activity_log.php content ---- */
    'Lacak semua tindakan dan aktivitas Anda' => 'Track all your actions and activities',
    'Aktivitas'                    => 'Activities',
    'Belum ada aktivitas'         => 'No activities found',
    'Aktivitas Anda akan muncul di sini saat Anda melakukan tindakan' => 'Your activities will appear here as you perform actions',
    'Pilih hotel terlebih dahulu' => 'Please select a hotel first',
    'Silakan pilih hotel untuk mengelola tipe kamar.' => 'Please select a hotel to manage room types.',

    /* ---- admin panel: performance_analytics.php content ---- */
    'Analitik Okupansi - Visualisasi Hunian Kamar' => 'Occupancy Analytics - Visualisasi Hunian Kamar',
    'Analitik Pendapatan - Visualisasi Pendapatan' => 'Revenue Analytics - Visualisasi Pendapatan',
    'Analitik Booking - Visualisasi Reservasi' => 'Booking Analytics - Visualisasi Reservasi',
    'Analitik Performa Kamar - Visualisasi Performa Kamar' => 'Room Performance Analytics - Visualisasi Performa Kamar',
    'Analitik Pelanggan - Visualisasi Pelanggan' => 'Customer Analytics - Visualisasi Pelanggan',
    'Dasbor Analitik Performa - Visualisasi Data TripVerse' => 'Performance Analytics Dashboard - Visualisasi Data TripVerse',
    'Ikhtisar'                     => 'Overview',
    'Okupansi'                     => 'Occupancy',
    'Performa Kamar'              => 'Room Performance',
    'Peringkat Performa Hotel'   => 'Hotel Performance Ranking',
    'Statistik Cepat per Tipe Kamar' => 'Quick Stats by Room Type',
    'Okupansi berdasarkan Lokasi' => 'Occupancy by Location',
    'Pendapatan berdasarkan Lokasi - Analisis Geografis' => 'Revenue by Location - Analisis Geografis',
    'Diagram Pai Distribusi Pendapatan' => 'Revenue Distribution Pie Chart',
    'Detail Data Visualisasi'    => 'Visualization Data Detail',
    'Booking Pendapatan Tertinggi' => 'Top Revenue Bookings',
    'Diagram Pai Metode Booking' => 'Booking Methods Pie Chart',
    'Analisis Lead Time'          => 'Lead Time Analysis',
    'Utilisasi Kamar berdasarkan Hari - Visualisasi Jadwal' => 'Room Utilization by Day of Week - Visualisasi Jadwal',
    'Analisis Segmentasi Pelanggan - Visualisasi Segmentasi' => 'Customer Segmentation Analysis - Visualisasi Segmentasi',
    'Distribusi Tipe Pelanggan'  => 'Customer Type Distribution',
    'Detail Segmentasi Pelanggan' => 'Customer Segmentation Detail',
    'Analisis Sumber Pelanggan - Visualisasi Channel' => 'Customer Source Analysis - Visualisasi Channel',
    'Top 10 Pelanggan berdasarkan Nilai - Visualisasi VIP' => 'Top 10 Customers by Value - Visualisasi VIP',
    'Analisis Customer Lifetime Value (CLV) - Visualisasi Nilai' => 'Customer Lifetime Value (CLV) Analysis - Visualisasi Nilai',
    '10 Hotel Berkinerja Terbaik' => 'Top 10 Performing Hotels',
    'Peringkat'                    => 'Rank',
    'Tingkat Okupansi'           => 'Occupancy Rate',
    'Tingkat Keberhasilan'      => 'Success Rate',
    'Tidak ada data hotel untuk periode ini' => 'No hotel data available for this period',

    'Ringkasan Statistik Promo' => 'Promo Statistics Overview',
    'Promo Aktif'                 => 'Active Promo',
    'Promo Tidak Aktif'          => 'Inactive Promo',
    'Total Digunakan'            => 'Total Used',
    'Cari promo berdasarkan nama atau kode...' => 'Search promo by name or code...',
    'Tambah Promo Baru'          => 'Add New Promo',
    'Daftar Promo'                => 'Promo List',
    'Nama Promo'                  => 'Promo Name',
    'Tipe Diskon'                 => 'Discount Type',
    'Nilai'                        => 'Value',
    'Min. Pembelian'             => 'Min Purchase',
    'Tanggal Mulai'               => 'Start Date',
    'Tanggal Berakhir'           => 'End Date',
    'Kuota'                        => 'Quota',
    'Terpakai'                     => 'Used',
    '(Kedaluwarsa)'               => '(Expired)',
    'Tanpa Batas'                  => 'Unlimited',
    'Lihat detail penggunaan'    => 'View usage details',
    'Lihat Penggunaan'           => 'View Usage',
    'Nonaktifkan'                  => 'Deactivate',
    'Aktifkan'                     => 'Activate',
    'Persentase'                   => 'Percentage',
    'Tetap'                        => 'Fixed',
    'Tidak Aktif'                  => 'Inactive',

    'Buat Owner Baru'           => 'Create New Owner',
    'Buat Owner'                  => 'Create Owner',
    'Semua Owner'                 => 'All Owners',
    'Belum ada owner'            => 'No owners yet',

    'Kelola Hotel'            => 'Manage Hotels',
    'Kelola Kamar'            => 'Manage Rooms',
    'Fasilitas Tambahan'      => 'Extra Facilities',
    'Log Aktivitas'           => 'Activity Log',
    'Pemilik Hotel'           => 'Hotel Owner',
];

if (!function_exists('t')) {
    /**
     * Translate one string. Falls back to the Indonesian source text.
     */
    function t($text)
    {
        if (tv_lang() === 'id') {
            return $text;
        }
        return $GLOBALS['TV_DICT'][$text] ?? $text;
    }
}

if (!function_exists('te')) {
    /**
     * Translate and HTML-escape in one step.
     */
    function te($text)
    {
        return htmlspecialchars(t($text), ENT_QUOTES, 'UTF-8');
    }
}

if (!function_exists('tv_lang_url')) {
    /**
     * Current URL with the language swapped, preserving other query params.
     */
    function tv_lang_url($lang)
    {
        $params = $_GET;
        $params['lang'] = $lang;
        $path = strtok($_SERVER['REQUEST_URI'], '?');
        return htmlspecialchars($path . '?' . http_build_query($params), ENT_QUOTES, 'UTF-8');
    }
}
